[
    {
        "key": "dbln",
        "value": "%7B%2261580395796824%22%3A%22kI2LcTSm%22%2C%2261575856418054%22%3A%220bI6OdQx%22%7D",
        "domain": "facebook.com",
        "path": "/login/device-based/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.337Z",
        "lastAccessed": "2025-09-05T13:32:04.337Z"
    },
    {
        "key": "datr",
        "value": "YOi5aGzXOM4OrnYfuuMaZVIw",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.337Z",
        "lastAccessed": "2025-09-05T13:32:04.337Z"
    },
    {
        "key": "sb",
        "value": "YOi5aIZRrnY-lFSYN9Zsf9Ue",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.337Z",
        "lastAccessed": "2025-09-05T13:32:04.337Z"
    },
    {
        "key": "locale",
        "value": "en_US",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.337Z",
        "lastAccessed": "2025-09-05T13:32:04.337Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B999x501x2.4375",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.337Z",
        "lastAccessed": "2025-09-05T13:32:04.337Z"
    },
    {
        "key": "c_user",
        "value": "61575856418054",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.337Z",
        "lastAccessed": "2025-09-05T13:32:04.337Z"
    },
    {
        "key": "xs",
        "value": "6%3A_DmaSDBfnI1jBw%3A2%3A1757052713%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.337Z",
        "lastAccessed": "2025-09-05T13:32:04.337Z"
    },
    {
        "key": "pas",
        "value": "61580395796824%3Ae1HfXGNKd9%2C61575856418054%3AJV8Bi1cGsn",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.337Z",
        "lastAccessed": "2025-09-05T13:32:04.337Z"
    },
    {
        "key": "ps_l",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.337Z",
        "lastAccessed": "2025-09-05T13:32:04.337Z"
    },
    {
        "key": "ps_n",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.338Z",
        "lastAccessed": "2025-09-05T13:32:04.338Z"
    },
    {
        "key": "fr",
        "value": "0B8awXYngrIvUizZv.AWe9bm3FztXLN3uJqt735meOvqWfNcuHo2VLrzCtjPRKZwLexqU.Bouehg..AAA.0.0.BouuY5.AWcC9jmtnuiap4IBiMxJGsjQN7w",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.338Z",
        "lastAccessed": "2025-09-05T13:32:04.338Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2913%3Btimestamp%3A1757079097",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.338Z",
        "lastAccessed": "2025-09-05T13:32:04.338Z"
    },
    {
        "key": "fbl_st",
        "value": "100423567%3BT%3A29284651",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-09-05T13:32:04.338Z",
        "lastAccessed": "2025-09-05T13:32:04.338Z"
    }
]
